module: KituraTemplateEngine
author: IBM
github_url: https://github.com/IBM-Swift/Kitura-TemplateEngine/

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, Kitura-TemplateEngine.xcodeproj, -target, KituraTemplateEngine, LIBRARY_SEARCH_PATHS=.build/debug]

