module: KituraNet
author: IBM
github_url: https://github.com/IBM-Swift/Kitura-net/

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, Kitura-net.xcodeproj, -target, KituraNet, LIBRARY_SEARCH_PATHS=.build/debug]

