# .travis.yml for Kitura Swift Packages

# whitelist
branches:
  only:
    - master
    - develop
    - /^issue.*$/

notifications:
  slack:
    secure: "P0r4xHJ1C6siPNtB0HM8kcRDGrD7PX0iY3UrDwRN41isiw1IpjNjNOvtzEzATyIkkpMlMXEq3QBdEsxZCwIKYUZHCy99CSkoY/brUdIJgaC92XZzP7BucQAhbweilVX4YcB8CmfKJ9b5I/+7o7bbnOlcVDUkd29QuMb0nUy2rXl6xZVLJ/9BmFSsffAquPjfdQKq/xh/hIbaBtHLDVxxQ4Q/DeDJ+FLkG16tFAvEj9EMDgeFcKZF9pOpFrCdpwj1Bg8NLB5vZqizxgr9xK4lBBr7LBrwhwfzvxs8DAjwWSUZkZEhPfoRzSBZ0tYeqH2V3dL8B9eEPVyfDawq8DXQcjMVIn5wpVQqNzzjuAXNlqhjT7PzjDccnU821uNs9nYDY5aug8pqC+ZaB1GSnt4Y0jH4NjSnEQIGeYwn3D4CiTwAGjO/OFJT5VV/DcKpdtzcuEbhCJyaPPfk4obgiUOOBEH6Ut932fqYfd70h7gupofFcctzsei3egAv9bff/PTIzhYsf5Vacj4i/hx+AaBK63BctKu8okcPne40OKms15dO/BB5AfFZYsN+sSOhzOpTzZpxS2tEqVJsVna0DcFX5cWzIMr0MonQYLr/uVB7mgE/VT8wETbVaEkSq/yqScOQRLM/ja/o273e3bv1EoRxYJPQSHQR/Du1le1E2dQS+Qc="

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8.2
      sudo: required

before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git

script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
